@APIWeb_HostAddress = https://localhost:7048

POST {{APIWeb_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "content" : "cheese, pineapple, ham",
    "isGlutenFree": false,
    "price": 12.4
}

###
